substitutions:
  name: "laterna"

esphome:
  name: "${name}"
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

dashboard_import:
  package_import_url: github://monoapp3/Laterna/edit/main/ESPHome Config/laterna.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Laterna Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO21
    num_leds: 60
    rgb_order: BRG
    name: "Laterna WS2812B Light"
